package error

import "testing"

// defer-panic-and-recover为了处理真正的异常，而不是普通的错误error
func TestOne(t *testing.T) {

}

func TestTwo2(t *testing.T) {

}
